- src/ArrayToXml.php
Using DOMDocument::createElement() will check if the array key name is valid as an xml tagname. If it's not (like with numeric keys) a DOMException with DOM_INVALID_CHARACTER_ERR will be raised.
One thing that should be considered is that spaces in a tagname are automatically converted to '_' at the moment, but would normally also result in the exception. So there are 2 paths to consider:
1. try and fix the tagname automatically. Downside here is that when the xml is parsed back to an array, some keys might be different, with no way to tell which.
2. let DOMDocument parse the tagname and raise an exception if necessary.
> DomDocument

- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
```php
['user' => ['foo', 'bar']];
```
```xml
<root>
<user>foo</user>
<user>bar</user>
</root>
```
```php
['user' => User::all()]
```
```xml
<root>
<user>
<id>1</id>
<email>...</email>
</user>
<user>
<id>2</id>
<email>...</email>
</user>
...
</root>
```
Signed-off-by: crynobone <crynobone@gmail.com>
> Add support to collection arrays, and dynamically XML convertion when keys is numeric (when possible).

- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
New feature that allow to have `<tagName attr1="value" />`
Usage
```
$array = [
'Good guy' => [
'_attributes' => ['attr1' => 'value']
'name' => 'Luke Skywalker',
'weapon' => 'Lightsaber'
],
'Bad guy' => [
'name' => 'Sauron',
'weapon' => 'Evil Eye'
]
];
$result = ArrayToXml::convert($array);
```
Will give
```xml
<root>
<Good_guy attr1="value">
<name>Luke Skywalker</name>
<weapon>Lightsaber</weapon>
</Good_guy>
<Bad_guy>
<name>Sauron</name>
<weapon>Evil Eye</weapon>
</Bad_guy>
</root>
```
You can also want to have something like that
```<weapon price="55" stock="2">LightSaber</weapon>```
for that we''ll have XML array like that
phpunit has been addded
```
$array = [
'Good guy' => [
'_attributes' => ['attr1' => 'value']
'name' => 'Luke Skywalker',
'weapon' => [ …
```
> Feat attribute xml

- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
I tried to create a XML in this case.
```php
$array = [
'movie' => [
[
'title' => [
'_attributes' => ['category' => 'SF'],
'_value' => 'STAR WARS'
]
],
[
'title' => [
'_attributes' => ['category' => 'Children'],
'_value' => 'tom & jerry'
]
]
]
];
$result = ArrayToXml::convert($array);
```
This results expected.
```xml
<root>
<movie>
<title category="SF">STAR WARS</title>
</movie>
<movie>
<title category="Children">tom &amp; jerry</title>
</movie>
</root>
```
But, test fails.
```
Spatie\ArrayToXml\ArrayToXml::convertElement(): unterminated entity reference
```
It was fixed because it is very convenient library.
> Fixed an error when there is a special character to the value set in _value

- composer.json
I don't see any reason why it's needed under `"require"` section
> Move phpunit-snapshot-assertions to require-dev

- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
- tests/__snapshots__/ArrayToXmlTest__it_can_handle_attributes_as_collection__1.xml
Change in behaviour:
```xml
// previous
+<root>
+  <user name="twee" age="12"/>
+</root>
// fixed
+<root>
+  <user name="een" age="10"/>
+  <user name="twee" age="12"/>
+</root>
```
Edit; I only now see that there was already someone running into the same problem. So I guess this fixes https://github.com/spatie/array-to-xml/issues/35
> Fixed attribute only collections being overridden

- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
- tests/__snapshots__/ArrayToXmlTest__it_can_handle_zero_values_in_beginning_of_basic_collection__1.xml
As reported in https://github.com/spatie/array-to-xml/issues/111, it appears that:
`ArrayToXml::convert(['a' => ['0', '1']])`
will result in:
`<root><a>1</a></root>`
while:
`ArrayToXml::convert(['a' => ['1', '0']])`
results in:
`<root><a>1</a><a>0</a></root>`
Reason for that is that `empty` evaluates as true for 0 as string, 0 as float and 0 as integer:
https://github.com/spatie/array-to-xml/blob/68a181261df9ba16688abb87d8658638157b8f90/src/ArrayToXml.php#L171
Requesting a review for my proposed solution as it may be a breaking change.
> Fix for zero values interpreted as empty

- src/ArrayToXml.php
- tests/__snapshots__/ArrayToXmlTest__it_can_handle_numeric_keys__1.php
As mentioned in issue #114, there currently is an issue with the XML output when using numeric keys, which end up being duplicated, thus not respecting the initial structure.
To reproduce the issue, you can use the example in the aforementioned issue, or the following snippet: 
```
<?php
include_once('./src/ArrayToXml.php');
$data = array(
array(
'id' => 1,
'entry' => 'aze',
),
array(
'id' => 2,
'entry' => 'rty',
),
);
$xml = \Spatie\ArrayToXml\ArrayToXml::convert(['__numeric' => $data]);
var_dump($xml);
```
Currently, this snippet will give you the following output:
```
<root>
<numeric_0>
<id>1</id>
<entry>aze</entry>
</numeric_0>
<numeric_0>
<id>2</id>
<entry>rty</entry>
</numeric_0>
<numeric_1>
<id>1</id>
<entry>aze</entry>
</numeric_1>
<numeric_1>
<id>2</id> …
```
> Fix XML structure when using numeric keys

- README.md
- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
- tests/__snapshots__/ArrayToXmlTest__it_can_drop_xml_declaration__1.php
Fixes #144 
Simple setter which allows dropping XML declaration. Useful for generating SOAP envelope.
Base snapshot driver must be used to see effects of this change.
> Add support for dropping XML declaration

- README.md
- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
- tests/__snapshots__/ArrayToXmlTest__it_accepts_an_xml_standalone_value__1.php
as seen on https://stackoverflow.com/questions/452361/how-to-make-domdocument-write-standalone-yes-in-php
> add $xmlStandalone as a new parameter

- README.md
- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
- tests/__snapshots__/ArrayToXmlTest__it_can_handle_custom_keys_containing_colon_character__1.php
- tests/__snapshots__/ArrayToXmlTest__it_can_handle_custom_keys_containing_colon_character__1.txt
Allows for colon characters as part of the custom key syntax by backslash escaping them. 
e.g. `__custom:ns\:parameter:1` will resolve to a custom key of `ns:parameter`
I really appreciate how easy this package is making it to build XML for interaction with a partner's SOAP interface Unfortunately, I have encountered a scenario requiring colon-delimited custom keys, which isn't possible (that I know of) using the current explode() approach. This modification would allow more flexibility in the custom key name.
Thank you so much for this and so many other packages, and for considering this PR!
> Add escapable colons in custom keys

- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
- tests/__snapshots__/ArrayToXmlTest__it_can_convert_an_array_with_null_value_to_xml__1.xml
Regarding this issue. https://github.com/spatie/array-to-xml/issues/169
This will allow null to be present in array.
For example, convert this array 
```
$arr = [
'test' => null,
];
ArrayToXml::convert($arr);
```
to below xml
```
<root>
<test/>
</root>
```
> allow null inside array to be converted to xml

- README.md
- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
- tests/__snapshots__/ArrayToXmlTest__it_can_add_processing_instructions__1.txt
I came across this issue #143 and also needed this feature. It adds the method `addProcessingInstruction($target, $data)` to the `ArrayToXML` object and can be used like this:
```php
$arrayToXml = new ArrayToXml($array);
$arrayToXml->addProcessingInstruction('qbxml', 'version="13.0"');
$result = $arrayToXml->toXml();
```
Which would generate:
```xml
<?qbxml version="13.0"?>
<root><Good_guy><name>Luke Skywalker</name><weapon>Lightsaber</weapon></Good_guy><Bad_guy><name>Sauron</name><weapon>Evil Eye</weapon></Bad_guy></root>
```
Multiple processing instructions can be added, and they will always be prepended above the root element.
I figured this may not be used enough to justify adding it to the `convert()` method arguments, but am happy to add it there if wanted.
> Ability to add processing instructions

- src/ArrayToXml.php
fix #186 ($string) of type string is deprecated in PHP 8.1
> PHP 8.1 fix deprecated null parameters

- src/ArrayToXml.php
Incorrect method call to `->saveXml()` (Should be `->saveXML()`).
It's not a bug, but merely a code smell issue.
Doesn't merit a release on it's own.
> V2 - Code smell ('incorrect' method call)

- .github/workflows/dependabot-auto-merge.yml
- Bump `dependabot/fetch-metadata` from 1.3.5 to 1.3.6
Backports spatie/array-to-xml#210
> Upgrade `dependabot/fetch-metadata`

- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
- tests/__snapshots__/ArrayToXmlTest__it_can_convert_an_array_with_empty_string_and_null_value_to_xml__1.xml
- tests/__snapshots__/ArrayToXmlTest__it_can_convert_an_array_with_empty_string_and_null_value_to_xml_with_option__1.xml
as follow up of https://github.com/spatie/array-to-xml/pull/225
revert converting null to xsi:nil, it will be enabled only by option
> Conver null based on option

- CHANGELOG.md
- src/ArrayToXml.php
- tests/ArrayToXmlTest.php
- tests/__snapshots__/ArrayToXmlTest__it_can_convert_boolean_values_to_xml_representation__1.xml
- tests/__snapshots__/ArrayToXmlTest__it_can_not_convert_boolean_values_to_xml_representation__1.xml
Currently, boolean values are converted incorrectly. Only `true` value is converted to 1 which is allowed value. `false` is converted as an empty attribute, which is incorrect.
Based on https://www.w3.org/TR/xmlschema-2/#boolean
`true, false, 1, 0` are allowed values.
We don't want to break previous behavior so that feature can be enabled by option.
> Add proper boolean conversion to xml representation

- .php-cs-fixer.dist.php
- composer.json
- src/ArrayToXml.php
Using php-cs-fixer's rule [`nullable_type_declaration_for_default_null_value`](https://cs.symfony.com/doc/rules/function_notation/nullable_type_declaration_for_default_null_value.html#rule-nullable-type-declaration-for-default-null-value).
Also add the branch alias for 3.x
> Fix explicit nullable parameter for PHP 8.4 compatibility

- src/ArrayToXml.php
This PR introduces the ability to pass options to the [DOMDocument's saveXML method](https://www.php.net/manual/en/domdocument.savexml.php).
This allows the use of [LIBXML_NOEMPTYTAG](https://www.php.net/manual/en/libxml.constants.php) and [LIBXML_NOXMLDECL](https://www.php.net/manual/en/libxml.constants.php).
> Allow passing of saveXML options
